// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy3UavEs080RMW9-PhhpyRmOTiTltymAA',
    appId: '1:281557603522:web:ca87b8ad4b0d4478b4175b',
    messagingSenderId: '281557603522',
    projectId: 'edf-flutter-f61b9',
    authDomain: 'edf-flutter-f61b9.firebaseapp.com',
    storageBucket: 'edf-flutter-f61b9.appspot.com',
    measurementId: 'G-F1ZSN5GGK9',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALSqnmuy2sh5PUVR9do0sYNH-6kA5N6MU',
    appId: '1:281557603522:ios:6f9d719c7c159232b4175b',
    messagingSenderId: '281557603522',
    projectId: 'edf-flutter-f61b9',
    storageBucket: 'edf-flutter-f61b9.appspot.com',
    iosBundleId: 'com.example.edfFlutter',
  );
}
